config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get 'posts', to: 'posts#index'

  get 'posts/new', to: 'posts#new'

  get 'posts/:id', to: 'posts#show', as: :post

  post 'posts', to: 'posts#create'

  delete 'posts/:id', to: 'posts#destroy', as: :delete_post

  get 'posts/:id/edit', to: 'posts#edit', as: :edit_post

  patch 'posts/:id', to: 'posts#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
        @posts = Post.all.order("created_at DESC")
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to @post, notice: "You created a new post"
        else
            render :new, alert: "Your post was not  created"     
        end
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notice: "Post was successfully updated"
        else
            render :edit, alert: "Your post was not updated"
        end
    end

    def destroy
        @post.destroy

        redirect_to posts_path, notice: "Your post was deleted!"
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD-messanger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.submit %>
<% end %>

app/views/posts/_shared.html.erb
    <%= link_to "Edit", edit_post_path(post) %>
    <%= link_to "Delete", delete_post_path(post), method: :delete, data: {
        confirm: "Are you sure you want to delete this post?"
    }  %>

app/views/posts/edit.html.erb
<h1>Edit Post </h1>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1>Posts page</h1>

<%= link_to "New post", posts_new_path %>
<br>

<% @posts.each do |post| %>
    <p>
        [<%= post.id %>] <%= post.title %>
    </p>
    <p>
        <%= post.body %>
    </p>

    <%= link_to "Show", post %>

    <%= render 'posts/shared', post: post %>

<% end %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<h1>Showing post</h1>

<h3><%= @post.title  %></h3>

<p><%= @post.body %></p>


<%= link_to "All Posts", posts_path %>

<%= render 'posts/shared', post: @post %>